specfile_path: anaconda.spec
upstream_package_name: anaconda
upstream_tag_template: anaconda-{version}-1
copy_upstream_release_description: true
actions:
  post-upstream-clone:
    - ./autogen.sh
    - ./configure
    - sed -i 's/use_cockpit\ 1/use_cockpit 0/g' anaconda.spec
  create-archive:
    - "make release"
    - 'bash -c "ls -1 anaconda-*.tar.bz2"'
jobs:
  # For Fedora branching change the `dist_git_branches` on fXX-release to 'fxx' value
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches: main

  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-rawhide

  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-rawhide
      additional_repos:
        # This repository contains fixup of Rawhide broken environment.
        # Mainly useful when there is a package which is not yet in Rawhide but build is available.
        - "https://fedorapeople.org/groups/anaconda/repos/anaconda_fixup_repo/"

  - job: copr_build
    trigger: commit
    metadata:
      targets:
        - fedora-rawhide
      branch: master
      owner: "@rhinstaller"
      project: Anaconda
      additional_repos:
        # This repository contains fixup of Rawhide broken environment.
        # Mainly useful when there is a package which is not yet in Rawhide but build is available.
        - "https://fedorapeople.org/groups/anaconda/repos/anaconda_fixup_repo/"
      preserve_project: True

  # For Fedora branching change the `branch` for fXX-devel
  - job: copr_build
    trigger: commit
    metadata:
      targets:
        - fedora-latest
      branch: f36-devel
      owner: "@rhinstaller"
      project: Anaconda-devel
      preserve_project: True
      additional_repos:
        - "copr://@storage/blivet-daily"
        # This repository contains fixup of Rawhide broken environment.
        # Mainly useful when there is a package which is not yet in Rawhide but build is available.
        - "https://fedorapeople.org/groups/anaconda/repos/anaconda_fixup_repo/"
