name: Run validation tests
on: pull_request

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: [self-hosted, kstest]
    timeout-minutes: 30
    env:
      TARGET_BRANCH_NAME: origin/rhel-8

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Rebase to current ${{ env.TARGET_BRANCH_NAME }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git log --oneline -1 ${{ env.TARGET_BRANCH_NAME }}
          git rebase ${{ env.TARGET_BRANCH_NAME }}

      # build container if files for dockerfile changed in the PR
      - name: Build anaconda-ci container
        run: make -f Makefile.am anaconda-ci-build

      - name: Run tests in anaconda-ci container
        run: |
          # put the log in the output, where it's easy to read and link to
          make -f Makefile.am container-ci || { cat test-logs/test-suite.log; exit 1; }

      - name: Upload test and coverage logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: test-logs/*

  rpm-tests:
    runs-on: [self-hosted, kstest]
    timeout-minutes: 30
    env:
      TARGET_BRANCH_NAME: origin/rhel-8

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Rebase to current ${{ env.TARGET_BRANCH_NAME }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git log --oneline -1 ${{ env.TARGET_BRANCH_NAME }}
          git rebase ${{ env.TARGET_BRANCH_NAME }}

      - name: Build RPM test container
        run: make -f Makefile.am anaconda-rpm-build

      - name: Run RPM tests in container
        run: make -f Makefile.am container-rpm-test

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: 'logs-rpm-test (${{ matrix.ci_tag }})'
          path: test-logs/*
